### ISSUE TITLE
Implementing arithmetic operators

### ISSUE THREAD

**Issue by kyp44** [ObjectBoxPC/rust-infinitable#1]
Hi, this is a nice crate that is better semantically than using `Option` to represent infinite values.

The one feature that would be useful in some situations would be to implement arithmetic operators using the standard rules of the [extended real numbers](https://en.wikipedia.org/wiki/Extended_real_number_line). For undefined operator results, an `Option<Infinitable<T>>` can be used as the operator `Output` type **or** and `Undefined` variant could be added for `Infinitable`, though it's not immediately clear to me which approach would be better.

If you like the idea of implementing these, I'd be happy to implement it and submit a PR.

**Comment by ObjectBoxPC** [comment]
Hi, thanks for your feedback.

I'm hesitant to implement full arithmetic here because there are at least two different ways to extend the real numbers with an "infinity." Another is the [projectively extended real numbers](https://en.wikipedia.org/wiki/Projectively_extended_real_line), which has only one infinite value, and there is the similar [Riemann sphere](https://en.wikipedia.org/wiki/Riemann_sphere) for complex numbers (this crate is not limited to real numbers).

I admit there are problems that arise when trying to represent the projectively extended reals or the Riemann sphere, which don't with the (affinely) extended reals. After giving it some thought I'm thinking maybe we could implement the arithmetic operators corresponding to the extended reals and add a separate type for this (`SinglePointInfinitable`?) with arithmetic operators corresponding to the projectively extended reals and Riemann sphere.

**Comment by ObjectBoxPC** [comment]
A major question I have is how to handle dividing a finite value by zero, where the underlying type has a "zero" value to speak of. I don't think there's a good way to generically test for such a zero value in the denominator, so the operator here would have to defer to the underlying type's division operator and its own handling of this situation (panic for integer types, floating-point infinity for floating-point types).

**Comment by kyp44** [comment]
Yeah, I was thinking only of the affinely extended reals, but I like the idea of a separate type for the projectively extended arithmetic if you think that would be useful. That's a good point about the division by zero problem. We would need to be able to detect zeros because division is defined in the (affinely) extended reals for all extended divisors except zero. If you're alright with adding a dependency, the [`num`](https://docs.rs/num/latest/num/index.html) crate would help here, which provides a variety of traits implemented for primitive number types, including the [`Zero`](https://docs.rs/num/latest/num/trait.Zero.html) trait that has an [`is_zero`](https://docs.rs/num/latest/num/trait.Zero.html#tymethod.is_zero) method. To be consistent, I would be inclined to handle purely finite division by zero using whatever way we represent undefined results (`Option` or an `Undefined` variant) rather than relying on the underlying type behavior for division by zero, which is likely a panic.

Likewise, we would need to test finite values for being positive or negative. This is needed since, for example  ∞ / a = ∞ when a > 0, but ∞ / a = -∞ for a < 0. The `num` crate also provides [`Signed`](https://docs.rs/num/latest/num/trait.Signed.html) and [`Unsigned`](https://docs.rs/num/latest/num/trait.Unsigned.html) traits for this. However, I whipped up a little prototype to a concern I had about this, and found it best to implement extended division when the finite numeric type implements `Zero + Ord` so we can just use `n > 0` to test for positivity (or `n  < 0` for negativity) as this works for both signed and unsigned types.

Another fundamental question would be how to handle the case when extended operations are undefined. One natural choice is `Option<Infinitable<T>>`, but I think returning options from every operation instead of operations on two `Infinitable<T>` yielding just another `Infinitable<T>` (as is the case for normal numbers) would be pretty awkward when using actual operators. The other option is of course to add a `Nan` or `Undefined` variant to the `Infinitable` enum, but this would also be a bit annoying to have to handle this variant everywhere, even if operations involving them are straightforward. This would also lead to the famous  `Nan` propagation issue that you get with floats. A third option would be to just panic for undefined operations just like regular numbers do when, for example, dividing by zero, and special methods could be added for the "try" version that would return an `Option` instead of panicking. Since these would use actual method syntax instead of operators, returning `Option` for these would not be awkward. What are your thoughts on the best approach for this?

**Comment by ObjectBoxPC** [comment]
> If you're alright with adding a dependency, the `num` crate would help here, which provides a variety of traits implemented for primitive number types, including the `Zero` trait that has an `is_zero` method. To be consistent, I would be inclined to handle purely finite division by zero using whatever way we represent undefined results (`Option` or an `Undefined` variant) rather than relying on the underlying type behavior for division by zero, which is likely a panic.

One of my goals is to is to keep `Infinitable` generic across as many types as possible, but if it's necessary to depend on a particular trait for arithmetic operations then I think it's is fine. (Side note: We could depend on `num-traits` instead of `num` to reduce the amount of dependent code.)

We will need to document all this thoroughly, especially:

* The `Zero` trait is required to implement certain operations. (I believe these would include division, for reasons already discussed, as well as multiplication, in order to check for zero times infinity.)
* Arithmetic operations do not fully preserve operations on the underlying type. That is, there will be some cases where `Finite(x) [op] Finite(y) != Finite(x [op] y)`.
* Any special handling of the pre-existing non-finite values of floating-point types (infinity, negative infinity, and NaN).

> Likewise, we would need to test finite values for being positive or negative. ...found it best to implement extended division when the finite numeric type implements `Zero + Ord` so we can just use `n > 0` to test for positivity (or `n < 0` for negativity) as this works for both signed and unsigned types.

This makes sense.

> Another fundamental question would be how to handle the case when extended operations are undefined.

I would lean towards the third option of panicking on undefined operations, and in fact I found the [magnitude](https://crates.io/crates/magnitude), which does essentially everything this crate does already (!) and takes this approach. (Although note that it leaves more operations undefined and has a slight theoretical difference in how it checks the sign for multiplication and division [it accepts `PartialOrd` and thus treats any values that are incomparable with zero the same as zero].)

**Comment by kyp44** [comment]
I appreciate your desire for documentation rigor. I also like the panicking idea and, again, we could always add methods like `checked_div` and whatnot to return an `Option<Infinitable<T>>` instead. It could also be worth using `Result` instead and defining an error enum with more specific things that can go wrong (e.g. divide by zero, or simply undefined). A design question here is, in the `Finite(a) [op] Finite(b)` case, would we just let the underlying operation panic like it normally would or call the checked version using additional `num-traits` such as [`CheckedAdd`](https://docs.rs/num-traits/latest/num_traits/ops/checked/trait.CheckedAdd.html). It probably just makes sense to focus on the panicking versions first and maybe add these later.

I agree that it makes sense to only implement arithmetic traits for types that satisfy certain `num-traits` traits as required since those are generally types for which certain operations make sense and are sufficiently defined for purposes of extended arithmetic. I likewise agree that care should be taken to make `Infinitable` be as general as possible in its trait bounds. As an example, I'm pretty certain that  extended addition on `Infinitable<T>` only requires `T: Add` so wouldn't require any `num-traits` bounds at all.

I also had not found the `magnitude` crate, and it does seem to basically serve the same purpose as this one. Given that, if you're still interested in further maintaining this crate, we could use `magnitude` as a guide as needed for how to implement arithmetic in a robust and general way.

**Comment by ObjectBoxPC** [comment]
> A design question here is, in the `Finite(a) [op] Finite(b)` case, would we just let the underlying operation panic like it normally would or call the checked version using additional `num-traits` such as `CheckedAdd`.

Note that division by zero leads to a panic for integer types, but not floating-point types. If we always defer to the operation on the underlying type, `Finite(1.0) / Finite(0.0)` would result in `Finite(f64::INFINITY)`; similarly, `Finite(0.0) / Finite(0.0)` would result in `Finite(f64::NAN)`. For "non-checked" division I would prefer returning `Infinitable::Infinity` in the first case and panicking in the second case.

> ...we could always add methods like `checked_div` and whatnot to return an `Option<Infinitable<T>>` instead. It could also be worth using `Result` instead and defining an error enum with more specific things that can go wrong...

I would prefer returning an `Option` simply because I think it would be worth implementing the same `Checked*` traits in the `num-traits` crate.

> As an example, I'm pretty certain that extended addition on `Infinitable<T>` only requires `T: Add` so wouldn't require any num-traits bounds at all.

Yes, I agree.

> ...we could use `magnitude` as a guide as needed for how to implement arithmetic in a robust and general way.

Yes, I will probably look to that crate for some guidance (without directly copying the code, of course).

**Comment by kyp44** [comment]
Awesome! Looks like you've started working on this. As i have an immediate need for it, I'm going to point my project at your development branch and start using the addition and subtraction.

That is a good point about simply implementing the `Checked*` traits in `num-traits` for checked operations and use the convention defined there. I agree that floating points might be tricky since they have `f64::INFINITY` and `f64::NAN` built-in and you'd rather use the `Infinitable::Infinity` variant in those cases.

**Comment by ObjectBoxPC** [comment]
@kyp44 sorry for the delay; I've just pushed my implementations of multiplication and division to that branch. I have a pull request open at #2 if you'd like to give further feedback there.
